const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.solid,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Platform,
		C3.Plugins.Arr,
		C3.Plugins.Clipboard,
		C3.Behaviors.Sin,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.EMI_INDO_LogMessage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.Browser.Acts.SetWindowSize,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.Browser.Cnds.OnResize,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.EMI_INDO_LogMessage.Acts.logMessage,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAdd,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.Clipboard.Acts.CopyText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsConsume,
		C3.Plugins.Eponesh_GameScore.Cnds.OnPaymentsConsume,
		C3.Plugins.Eponesh_GameScore.Acts.PaymentsPurchase,
		C3.Plugins.Eponesh_GameScore.Cnds.PaymentsIsPurchased,
		C3.Plugins.Eponesh_GameScore.Cnds.IsPaymentsPurchaseSuccessful,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Browser.Acts.RequestFullScreen
	];
};
self.C3_JsPropNameTable = [
	{mining: 0},
	{Rotate: 0},
	{pick: 0},
	{mine: 0},
	{mine2: 0},
	{mine3: 0},
	{ground: 0},
	{Anchor: 0},
	{usdt_: 0},
	{Browser: 0},
	{b1: 0},
	{usdtbg: 0},
	{PlatformInfo: 0},
	{mineinfo: 0},
	{Touch: 0},
	{GamePush: 0},
	{Usdt: 0},
	{Solid: 0},
	{digging_platform: 0},
	{settingsuiSquareBlack: 0},
	{settings_icon: 0},
	{mining_icon: 0},
	{comingsoon: 0},
	{pvp_icon: 0},
	{uiinfo: 0},
	{main_icon: 0},
	{Sprite: 0},
	{pick2: 0},
	{shop_: 0},
	{coin_icon: 0},
	{coin: 0},
	{chest_icon: 0},
	{rw_x2button: 0},
	{LocalStorage: 0},
	{rw_info: 0},
	{adv_icon: 0},
	{id_room: 0},
	{slot: 0},
	{my_hero: 0},
	{id_hero: 0},
	{Platform: 0},
	{flapster: 0},
	{Leaders_text: 0},
	{Leaders: 0},
	{wallet_: 0},
	{camera_: 0},
	{autoflash_: 0},
	{items: 0},
	{ironpickaxe_shopitem: 0},
	{goldpickaxe_shopitem: 0},
	{crimsonpickaxe_shopitem: 0},
	{emeraldpickaxe_shopitem: 0},
	{energy_bg: 0},
	{tag: 0},
	{InitialWidth: 0},
	{energy_bar: 0},
	{energy_text: 0},
	{user_id: 0},
	{settingsui: 0},
	{walletsui: 0},
	{settingstext: 0},
	{settingsuiexit: 0},
	{Clipboard: 0},
	{copybutton: 0},
	{shopbutton1: 0},
	{shopbutton2: 0},
	{shopbutton3: 0},
	{shopbutton4: 0},
	{shopbuttontext1: 0},
	{shopbuttontext2: 0},
	{shopbuttontext3: 0},
	{shopbuttontext4: 0},
	{loading_bg: 0},
	{coin_item1: 0},
	{coin_item2: 0},
	{coin_item3: 0},
	{Sine: 0},
	{Sine2: 0},
	{loading_bar: 0},
	{walletui: 0},
	{settingui2: 0},
	{walletuiexit: 0},
	{walletuiSquareBlack: 0},
	{walletuitext: 0},
	{connectusbutton: 0},
	{connectustext: 0},
	{walletmintext: 0},
	{b2: 0},
	{mineinfo2: 0},
	{mineinfo3: 0},
	{PrevY: 0},
	{CurY: 0},
	{DiffY: 0},
	{BoundToLayout: 0},
	{ScrollTo: 0},
	{scroll: 0},
	{LogMessage: 0},
	{diamondpickaxe_shopitem: 0},
	{uishopbg: 0},
	{nav_market: 0},
	{navshop_info: 0},
	{nav_market2: 0},
	{nav_market3: 0},
	{tg_star: 0},
	{shopbutton5: 0},
	{shopbuttontext5: 0},
	{mine_section: 0},
	{manat: 0},
	{click: 0},
	{x2_timer: 0},
	{item1_bought: 0},
	{item2_bought: 0},
	{item3_bought: 0},
	{item4_bought: 0},
	{item5_bought: 0},
	{Selected: 0}
];

self.InstanceType = {
	mining: class extends self.ISpriteInstance {},
	pick: class extends self.ISpriteInstance {},
	mine: class extends self.ISpriteInstance {},
	mine2: class extends self.ISpriteInstance {},
	mine3: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	usdt_: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	b1: class extends self.ISpriteInstance {},
	usdtbg: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	mineinfo: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Usdt: class extends self.ITextInstance {},
	digging_platform: class extends self.ISpriteInstance {},
	settingsuiSquareBlack: class extends self.ISpriteInstance {},
	settings_icon: class extends self.ISpriteInstance {},
	mining_icon: class extends self.ISpriteInstance {},
	comingsoon: class extends self.ITextInstance {},
	pvp_icon: class extends self.ISpriteInstance {},
	uiinfo: class extends self.ITextInstance {},
	main_icon: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	pick2: class extends self.ISpriteInstance {},
	shop_: class extends self.ISpriteInstance {},
	coin_icon: class extends self.ISpriteInstance {},
	coin: class extends self.ITextInstance {},
	chest_icon: class extends self.ISpriteInstance {},
	rw_x2button: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	rw_info: class extends self.ITextInstance {},
	adv_icon: class extends self.ISpriteInstance {},
	slot: class extends self.ISpriteInstance {},
	flapster: class extends self.ISpriteInstance {},
	Leaders_text: class extends self.ITextInstance {},
	Leaders: class extends self.IArrayInstance {},
	wallet_: class extends self.ISpriteInstance {},
	camera_: class extends self.ISpriteInstance {},
	autoflash_: class extends self.ISpriteInstance {},
	items: class extends self.ISpriteInstance {},
	ironpickaxe_shopitem: class extends self.ISpriteInstance {},
	goldpickaxe_shopitem: class extends self.ISpriteInstance {},
	crimsonpickaxe_shopitem: class extends self.ISpriteInstance {},
	emeraldpickaxe_shopitem: class extends self.ISpriteInstance {},
	energy_bg: class extends self.ISpriteInstance {},
	energy_bar: class extends self.ISpriteInstance {},
	energy_text: class extends self.ITextInstance {},
	user_id: class extends self.ITextInstance {},
	settingsui: class extends self.ISpriteInstance {},
	walletsui: class extends self.ISpriteInstance {},
	settingstext: class extends self.ITextInstance {},
	settingsuiexit: class extends self.ISpriteInstance {},
	Clipboard: class extends self.IInstance {},
	copybutton: class extends self.ISpriteInstance {},
	shopbutton1: class extends self.ISpriteInstance {},
	shopbutton2: class extends self.ISpriteInstance {},
	shopbutton3: class extends self.ISpriteInstance {},
	shopbutton4: class extends self.ISpriteInstance {},
	shopbuttontext1: class extends self.ITextInstance {},
	shopbuttontext2: class extends self.ITextInstance {},
	shopbuttontext3: class extends self.ITextInstance {},
	shopbuttontext4: class extends self.ITextInstance {},
	loading_bg: class extends self.ISpriteInstance {},
	coin_item1: class extends self.ISpriteInstance {},
	coin_item2: class extends self.ISpriteInstance {},
	coin_item3: class extends self.ISpriteInstance {},
	loading_bar: class extends self.ISpriteInstance {},
	walletui: class extends self.ISpriteInstance {},
	settingui2: class extends self.ISpriteInstance {},
	walletuiexit: class extends self.ISpriteInstance {},
	walletuiSquareBlack: class extends self.ISpriteInstance {},
	walletuitext: class extends self.ITextInstance {},
	connectusbutton: class extends self.ISpriteInstance {},
	connectustext: class extends self.ITextInstance {},
	walletmintext: class extends self.ITextInstance {},
	b2: class extends self.ISpriteInstance {},
	mineinfo2: class extends self.ITextInstance {},
	mineinfo3: class extends self.ITextInstance {},
	scroll: class extends self.ISpriteInstance {},
	LogMessage: class extends C3.Plugins.EMI_INDO_LogMessage.Instance {},
	diamondpickaxe_shopitem: class extends self.ISpriteInstance {},
	uishopbg: class extends self.ISpriteInstance {},
	nav_market: class extends self.ISpriteInstance {},
	navshop_info: class extends self.ITextInstance {},
	nav_market2: class extends self.ISpriteInstance {},
	nav_market3: class extends self.ISpriteInstance {},
	tg_star: class extends self.ISpriteInstance {},
	shopbutton5: class extends self.ISpriteInstance {},
	shopbuttontext5: class extends self.ITextInstance {}
}